---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: nginx
    labels:
      app: nginx
  spec:
    type: LoadBalancer
    selector:
      app: nginx
    ports:
      - port: 8088
        targetPort: 80
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nginx
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: menxiaoacrsea.azurecr.io/nginx
          ports:
          - containerPort: 80
        imagePullSecrets:
        - name: test-multiple-registry-key