---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: nginx-service
    labels:
      app: nginx
  spec:
    type: LoadBalancer
    selector:
      app: nginx
    ports:
      - port: 80
        targetPort: 80
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx-container
          image: nginx
          ports:
          - containerPort: 80
