apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: menxiao-k8s-pipeline-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: menxiao-k8s-demo
        secret: $KUBERNETES_SECRET_NAME
    spec:
      containers:
      - name: menxiao-k8s-demo-container
        image: menxiao/menxiao-k8s-demo:$DOCKER_IMAGE_TAG
        ports:
        - containerPort: 8080
