---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: tomcat-service
    labels:
      app: tomcat
  spec:
    type: LoadBalancer
    selector:
      app: tomcat
    ports:
      - port: 80
        targetPort: 8080
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: tomcat-deployment
  spec:
    replicas: 4
    template:
      metadata:
        labels:
          app: tomcat
      spec:
        containers:
        - name: tomcat-container
          image: tomcat:7.0-jre7
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
